name: artifact_challenge

on: [push]

env:
    ARTIFACT_NAME: myartifact

jobs:
    artifact_upload:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v1.0.0
              
            - name: Upload artifact
              uses: actions/upload-artifact@v1.0.0
              with: 
                name: ${{ env.ARTIFACT_NAME }}
                path: .
